version: 2.1

workflows:
  build-deploy:
    jobs:
      - build-deploy

jobs:
  build-deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
        # when lock file changes, use increasingly general patterns to restore cache
            - cachingimplementation-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Build and Deploy to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ashu-devops web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ashu-devops web
      - save_cache:
          paths:
            - ~/.m2
          key: cachingimplementation-{{ .Branch }}-{{ checksum "pom.xml" }}